# Generated by Django 4.2.7 on 2023-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_seller_banck_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
