# Generated by Django 4.2.7 on 2023-12-06 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_rename_orders_order_rename_products_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sellman",
            new_name="salesman",
        ),
    ]
