# Generated by Django 4.2.7 on 2023-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Images",
            field=models.ImageField(
                blank=True,
                default="assets/no-image.png",
                null=True,
                upload_to="assets/upload",
            ),
        ),
    ]
